const catalogue = {
outer:{name:'Essential duffle coat',label:'THE OUTER EDIT',category:'Outer',korean:'아우터 코트 더플 겨울 자켓 재킷',image:'assets/category-016.jpg',color:'Deep green',description:'떼뚜의 에센셜 더플코트. 익숙한 더플 실루엣과 딥 그린 컬러를 공식몰에서 만나보세요.',url:'https://www.tetu.co.kr/goods/goods_list.php?cateCd=016'},
knit:{name:'Kid mohair knit vest',label:'SOFT BY NATURE',category:'Knit',korean:'니트 베스트 조끼 모헤어 아이보리',image:'assets/category-017.jpg',color:'Ivory',description:'떼뚜의 키드 모헤어 니트 베스트. 일상에 부드럽게 더해지는 아이보리 컬러를 만나보세요.',url:'https://www.tetu.co.kr/goods/goods_list.php?cateCd=017'},
dress:{name:'V-neck wool balloon dress',label:'SIMPLY YOURSELF',category:'Dress',korean:'드레스 원피스 울 벌룬 카키',image:'assets/category-020.jpg',color:'Khaki',description:'떼뚜의 브이넥 울 벌룬 드레스. 간결한 실루엣과 차분한 카키 컬러를 공식몰에서 확인해 보세요.',url:'https://www.tetu.co.kr/goods/goods_list.php?cateCd=020'}
};
const motionPreference=window.matchMedia('(prefers-reduced-motion: reduce)');
const motionToggle=document.querySelector('.motion-toggle');
let motionPaused=motionPreference.matches;
function updateMotion(){document.body.classList.toggle('motion-paused',motionPaused);motionToggle.setAttribute('aria-pressed',String(motionPaused));motionToggle.setAttribute('aria-label',motionPaused?'배경 움직임 재생':'배경 움직임 일시정지');motionToggle.querySelector('span').textContent=motionPaused?'Motion off':'Motion on';motionToggle.querySelector('svg').innerHTML=motionPaused?'<path d="m7 4 8 6-8 6V4Z"/>':'<path d="M7 5v10M13 5v10"/>';}
motionToggle.addEventListener('click',()=>{motionPaused=!motionPaused;updateMotion();});motionPreference.addEventListener('change',event=>{motionPaused=event.matches;updateMotion();});updateMotion();
const header=document.querySelector('.site-header'),heroArt=document.querySelector('.hero-art');
const sections=[...document.querySelectorAll('main>section[id]')],navigation=[...document.querySelectorAll('.nav-pill a')];
let ticking=false;
function updateScroll(){const scroll=window.scrollY;header.classList.toggle('is-stuck',scroll>60);if(!motionPaused&&!motionPreference.matches&&scroll<1000&&innerWidth>600)heroArt.style.transform=`translateY(${Math.min(scroll*.13,100)}px) rotate(${Math.min(scroll*.0015,1)}deg)`;else heroArt.style.transform='';let active=sections[0].id;sections.forEach(section=>{if(section.offsetTop<=scroll+180)active=section.id;});navigation.forEach(link=>{const selected=link.hash===`#${active}`;link.classList.toggle('active',selected);if(selected)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current');});ticking=false;}
window.addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(updateScroll);ticking=true;}},{passive:true});window.addEventListener('resize',updateScroll);updateScroll();
if('IntersectionObserver'in window&&!motionPreference.matches){document.body.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(element=>observer.observe(element));}
const mobileMenu=document.querySelector('#mobile-menu'),menuToggle=document.querySelector('.menu-toggle');
function closeMenu(){mobileMenu.hidden=true;menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label','메뉴 열기');}
menuToggle.addEventListener('click',()=>{const open=mobileMenu.hidden;mobileMenu.hidden=!open;menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'메뉴 닫기':'메뉴 열기');});mobileMenu.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));document.addEventListener('click',event=>{if(!mobileMenu.hidden&&!mobileMenu.contains(event.target)&&!menuToggle.contains(event.target))closeMenu();});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!mobileMenu.hidden){closeMenu();menuToggle.focus();}});window.matchMedia('(min-width: 601px)').addEventListener('change',event=>{if(event.matches)closeMenu();});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{const filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(item=>{item.classList.toggle('active',item===button);item.setAttribute('aria-pressed',String(item===button));});let count=0;document.querySelectorAll('.product-card').forEach(card=>{card.hidden=filter!=='all'&&card.dataset.category!==filter;if(!card.hidden)count++;});document.querySelector('#category-link').href=(catalogue[filter]||catalogue.outer).url;document.querySelector('#filter-status').textContent=`${count}개의 아이템을 표시합니다.`;}));
const productDialog=document.querySelector('#product-dialog'),searchDialog=document.querySelector('#search-dialog');let lastFocus;
function openDialog(dialog){closeMenu();lastFocus=document.activeElement;dialog.showModal();}
document.querySelectorAll('dialog').forEach(dialog=>{dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>lastFocus?.focus({preventScroll:true}));dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});});
document.querySelectorAll('[data-product]').forEach(button=>button.addEventListener('click',()=>{const product=catalogue[button.dataset.product];document.querySelector('#product-photo').src=product.image;document.querySelector('#product-photo').alt=product.name+' — '+product.color;document.querySelector('#product-title').textContent=product.name;document.querySelector('#product-eyebrow').textContent=product.label;document.querySelector('#product-color').textContent=product.color;document.querySelector('#product-description').textContent=product.description;document.querySelector('#product-link').href=product.url;openDialog(productDialog);}));
const searchInput=document.querySelector('#search-input'),searchResults=document.querySelector('#search-results');
function renderSearch(){const query=searchInput.value.trim().toLocaleLowerCase();const matches=Object.values(catalogue).filter(product=>`${product.name} ${product.category} ${product.korean} ${product.color}`.toLocaleLowerCase().includes(query));searchResults.replaceChildren();if(!matches.length){const empty=document.createElement('p');empty.className='empty-results';empty.textContent='일치하는 카테고리가 없습니다. 아우터, 니트, 드레스로 다시 찾아보세요.';searchResults.append(empty);return;}matches.forEach(product=>{const link=document.createElement('a');link.className='search-result';link.href=product.url;link.target='_blank';link.rel='noopener noreferrer';link.innerHTML=`<img src="${product.image}" alt=""><span><strong>${product.category}</strong><small>${product.name}</small></span><span aria-hidden="true">↗</span>`;searchResults.append(link);});}
document.querySelectorAll('.search-trigger').forEach(button=>button.addEventListener('click',()=>{searchInput.value='';renderSearch();openDialog(searchDialog);searchInput.focus();}));searchInput.addEventListener('input',renderSearch);
